FROM node:16-alpine3.15 AS deps

WORKDIR /app
COPY ./backend/package*.json .
RUN npm install

# Production image
FROM node:16-alpine3.15 AS runner
WORKDIR /app

COPY ./backend .
COPY --from=deps /app/node_modules ./node_modules

CMD ["npm", "run", "dev"]