version: "3.9"

services:
  frontend:
    image: docker-react
    build: 
      dockerfile: Dockerfile.frontend
    ports:
    - 80:3000
  backend:
    image: docker-backend
    build:
      dockerfile: Dockerfile.backend
    ports:
      - 8080:8080
    depends_on:
      - mongo
  mongo:
    image: mongo
    restart: always
    ports:
      - 27018:27018
    
  